# Generated by Django 3.0.3 on 2020-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itm',
            name='Itm_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/56394ffa11970placeholder_food_item_2.png', max_length=500),
        ),
    ]
