# Generated by Django 3.0.3 on 2020-03-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0002_itm_itm_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itm',
            old_name='Itm_image',
            new_name='Itm_img',
        ),
    ]
