# Generated by Django 3.0.3 on 2020-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food1', '0003_auto_20200326_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itm',
            old_name='Itm_img',
            new_name='Itm_image',
        ),
    ]
